# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: rapidrails_api_development
  cache:
    <<: *default
    database: rapidrails_api_cache_development
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: rapidrails_api_queue_development
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: rapidrails_api_cable_development
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: rapidrails_api_test
  username: postgres
  password: postgres
  host: 127.0.0.1

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["CACHE_DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["CABLE_DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
